version: '3'
services:
  backend:
    volumes:
      - ./backend:/app/backend
    container_name: backend
    build: ./backend
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/reservation_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_PROFILES_ACTIVE=dev
      # デバッグ用の設定はbuild.gradleに移した。」
      # - JAVA_OPTS=-Dspring.devtools.restart.enabled=true -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    command: sh -c "./gradlew clean && ./gradlew build && ./gradlew bootRun"
    # tty: true # デバッグ用にターミナルを有効化
    depends_on:
      db:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    networks:
      - app-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: reservation_db
    volumes:
      - db-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf # my.cnfファイルをマウント
    ports:
      - '3306:3306'
    networks:
      - app-network
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'db',
          '-u',
          'root',
          '-p$${MYSQL_ROOT_PASSWORD}',
        ]
      interval: 10s
      retries: 3

  flyway:
    image: flyway/flyway:7.11.2
    command: -url=jdbc:mysql://db:3306/reservation_db -user=root -password=secret -locations=filesystem:/flyway/sql migrate
    volumes:
      - ./backend/src/main/resources/db/migration:/flyway/sql
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
